name: Python Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-python-code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: poetry install

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff .
        if: always()

      - name: Run ruff format
        run: ruff format --check .
        if: always()
